import numpy as np
A = np.array([[4,2,2],[2,5,3],[2,3,6]], dtype=float)
L = np.linalg.cholesky(A)
print('L =')
print(L)
print()
print('Verify L @ L.T =')
print(L @ L.T)

print()
B = np.array([[2,1,1],[1,3,2],[1,1,4],[1,2,1]], dtype=float)
Q, R = np.linalg.qr(B)
print('Q =')
print(Q)
print()
print('R =')
print(R)
print()
print('Verify Q @ R =')
print(Q @ R)
