"""
Run matmul_integer_4x4.onnx through the TinyXPU execution provider.

Loads the ONNX model generated by matmul.py, registers the TinyXPU EP plugin,
runs inference via Verilator simulation, and verifies the result against a
NumPy reference.

Usage:
    python scripts/run_matmul.py [path/to/libtinyxpu_ep.so]

If no path is given, defaults to build/onnx-plugin/libtinyxpu_ep.so relative
to the repo root.
"""

import ctypes
import os
import sys

import numpy as np
import onnx
import onnxruntime as ort
import tinyxpu_perf
from onnx import numpy_helper


def main() -> int:
    script_dir = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.join(script_dir, "..")

    model_path = os.path.join(script_dir, "matmul_integer_16x16.onnx")
    default_plugin = os.path.join(repo_root, "build", "onnx-plugin", "libtinyxpu_ep.so")
    plugin_path = os.path.abspath(sys.argv[1] if len(sys.argv) > 1 else default_plugin)

    if not os.path.exists(model_path):
        print(f"ERROR: model not found at {model_path}")
        print("Run `python scripts/matmul.py` first to generate it.")
        return 1
    if not os.path.exists(plugin_path):
        print(f"ERROR: plugin not found at {plugin_path}")
        print("Run `cmake .. -DSIM=ON && make -j` in the build directory first.")
        return 1

    print(f"ONNX Runtime version : {ort.__version__}")
    print(f"Model                : {model_path}")
    print(f"Plugin               : {plugin_path}")
    print()

    # =========================================================================
    # Register plugin EP and enumerate devices
    # =========================================================================
    print(f"Registering TinyXPU EP from: {plugin_path}")
    ort.register_execution_provider_library("SampleEP", plugin_path)
    print("Plugin EP registered successfully!\n")

    all_ep_devices = ort.get_ep_devices()
    tinyxpu_devices = []

    print(f"Found {len(all_ep_devices)} EP device(s):")
    for i, ep_device in enumerate(all_ep_devices):
        hw = ep_device.device
        hw_type = ort.OrtHardwareDeviceType(hw.type)
        print(f"  EP Device {i}:")
        print(f"    Name           : {ep_device.ep_name}")
        print(f"    Vendor         : {ep_device.ep_vendor}")
        print(f"    HW Device Type : {hw_type.name}")
        print(f"    HW Vendor      : {hw.vendor}")
        print(f"    HW Vendor ID   : 0x{hw.vendor_id:04x}")
        print(f"    HW Device ID   : 0x{hw.device_id:04x}")
        if "SampleEP" in ep_device.ep_name:
            tinyxpu_devices.append(ep_device)
    print()

    if not tinyxpu_devices:
        print("ERROR: TinyXPU EP device not found after registration.")
        return 1

    # =========================================================================
    # Create session (triggers GetCapability — EP claims MatMulInteger)
    # =========================================================================
    session_options = ort.SessionOptions()
    session_options.add_provider_for_devices(tinyxpu_devices, {})

    # Load the same .so via ctypes to access the exported perf getter.
    # dlopen() returns the same handle as ORT already loaded, so the global
    # g_last_perf is shared.
    lib = ctypes.CDLL(plugin_path)
    tinyxpu_perf.bind(lib)

    print("Creating inference session (EP will claim MatMulInteger)...")
    sys.stdout.flush()  # flush before C printf in GetCapabilityImpl fires
    session = ort.InferenceSession(model_path, sess_options=session_options)
    print("Session created.\n")

    # =========================================================================
    # Run inference
    # =========================================================================
    # Extract W from the model so the reference stays in sync with matmul.py.
    model_proto = onnx.load(model_path)
    W_ref = numpy_helper.to_array(
        next(t for t in model_proto.graph.initializer if t.name == "W")
    ).astype(np.int32)

    rng = np.random.default_rng(42)
    A = rng.integers(-64, 64, size=(512, 16), dtype=np.int8)

    expected = A.astype(np.int32) @ W_ref

    print(f"Input A (int8): shape {A.shape},  first row: {A[0]}")
    print(f"Weight W (int8, loaded from model):\n{W_ref.astype(np.int8)}")
    print()

    print("Running inference...")
    result = session.run(None, {"X": A})

    perf = tinyxpu_perf.get_last_perf(lib)
    tinyxpu_perf.print_perf(perf)
    print()

    Y = result[0]
    print(f"Output Y = A @ W (int32): shape {Y.shape},  first row: {Y[0]}")
    print(f"Expected (NumPy reference):           first row: {expected[0]}")
    print()

    # =========================================================================
    # Verify and cleanup
    # =========================================================================
    ok = np.array_equal(Y, expected)
    if ok:
        print("PASS: TinyXPU output matches NumPy reference.")
    else:
        print("FAIL: output mismatch!")
        print("Diff:")
        print(Y - expected)

    # =========================================================================
    # Sweep M: show how weight-load amortization improves with batch size
    # =========================================================================
    # MAC efficiency = PE utilization = M/(M+ROWS+COLS-2); both reduce to the same ratio.
    print("\n--- Weight-load amortization sweep (MAC eff = PE utilization) ---")
    # ridge BW = peak_compute / ai_systolic: DRAM bandwidth needed to be compute-bound.
    # Values below the ridge are memory-bound; above are compute-bound.
    print(
        f"{'M':>6}  {'ticks':>6}  {'PE util':>8}  {'AI (MAC/B)':>11}  {'wt reuse':>9}  {'overhead':>9}  {'ridge B/cyc':>12}"
    )
    print("-" * 77)

    M_values = [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]
    peak_macs = None
    for m in M_values:
        A_m = rng.integers(-64, 64, size=(m, 16), dtype=np.int8)
        session.run(None, {"X": A_m})
        p = tinyxpu_perf.get_last_perf(lib)
        o = p.obs
        peak_macs = o.hw_rows * o.hw_cols
        ridge_bw = peak_macs / p.ai_systolic if p.ai_systolic else float("inf")
        print(
            f"{m:>6}  {o.ticks_streaming:>6}  {p.mac_efficiency * 100:>7.1f}%"
            f"  {p.ai_systolic:>10.3f}  {o.M:>6}x  {p.overhead_frac * 100:>8.1f}%  {ridge_bw:>11.1f}"
        )
    if peak_macs is not None:
        print(f"\n  Peak compute = {peak_macs} MACs/cycle; memory-bound when DRAM BW < ridge B/cyc")

    del session
    ort.unregister_execution_provider_library("SampleEP")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
