"""
Run matmul_integer_4x4.onnx through the TinyXPU execution provider.

Loads the ONNX model generated by matmul.py, registers the TinyXPU EP plugin,
runs inference via Verilator simulation, and verifies the result against a
NumPy reference.

Usage:
    python scripts/run_matmul.py [path/to/libtinyxpu_ep.so]

If no path is given, defaults to build/libtinyxpu_ep.so relative to the
repo root.
"""
import os
import sys

import numpy as np
import onnxruntime as ort


def main() -> int:
    script_dir = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.join(script_dir, "..")

    model_path = os.path.join(script_dir, "matmul_integer_4x4.onnx")
    default_plugin = os.path.join(repo_root, "build", "onnx-plugin", "libtinyxpu_ep.so")
    plugin_path = os.path.abspath(sys.argv[1] if len(sys.argv) > 1 else default_plugin)

    if not os.path.exists(model_path):
        print(f"ERROR: model not found at {model_path}")
        print("Run `python scripts/matmul.py` first to generate it.")
        return 1
    if not os.path.exists(plugin_path):
        print(f"ERROR: plugin not found at {plugin_path}")
        print("Run `cmake .. -DSIM=ON && make -j` in the build directory first.")
        return 1

    print(f"ONNX Runtime version : {ort.__version__}")
    print(f"Model                : {model_path}")
    print(f"Plugin               : {plugin_path}")
    print()

    ort.register_execution_provider_library("SampleEP", plugin_path)

    ep_devices = [d for d in ort.get_ep_devices() if "SampleEP" in d.ep_name]
    if not ep_devices:
        print("ERROR: TinyXPU EP device not found after registration.")
        return 1

    session_options = ort.SessionOptions()
    session_options.add_provider_for_devices(ep_devices, {})

    session = ort.InferenceSession(model_path, sess_opts=session_options)

    # Test input: 4 rows x 4 columns, int8.
    # With the diagonal weight W = diag(1, 2, 3, 4), row i of Y is
    # row i of X element-wise scaled by [1, 2, 3, 4].
    A = np.array([
        [1, 2, 3,  4],
        [5, 6, 7,  8],
        [1, 1, 1,  1],
        [2, 2, 2,  2],
    ], dtype=np.int8)

    # Reference: same weight baked into matmul.py
    W_ref = np.array([
        [1, 0, 0, 0],
        [0, 2, 0, 0],
        [0, 0, 3, 0],
        [0, 0, 0, 4],
    ], dtype=np.int32)

    expected = A.astype(np.int32) @ W_ref

    print("Input A (int8):")
    print(A)
    print()
    print("Weight W (int8, baked in model):")
    print(W_ref.astype(np.int8))
    print()

    result = session.run(None, {"X": A})
    Y = result[0]

    print("Output Y = A @ W (int32, from TinyXPU EP):")
    print(Y)
    print()
    print("Expected (NumPy reference):")
    print(expected)
    print()

    if np.array_equal(Y, expected):
        print("PASS: TinyXPU output matches NumPy reference.")
    else:
        print("FAIL: output mismatch!")
        print("Diff:")
        print(Y - expected)
        ort.unregister_execution_provider_library("SampleEP")
        return 1

    ort.unregister_execution_provider_library("SampleEP")
    return 0


if __name__ == "__main__":
    sys.exit(main())
